### ISSUE TITLE
replace method for when PyPI and Anaconda names conflict

### ISSUE THREAD

**Issue by sgbaird** [marcelotrevisani/souschef#28]
Not urgent, and not a big deal either. Right now it's not too bad use `remove` and `append`:
```python
my_recipe["requirements"]["run"].remove("kaleido")
my_recipe["requirements"]["run"].append("python-kaleido")
```
Just thought it might be worth having:
```python
my_recipe["requirements"]["run"].replace("kaleido", "python-kaleido")
```
Feel free to ignore/close. Like I said not urgent, and it's just some syntactic sugar.

**Comment by marcelotrevisani** [comment]
Yeah, that would be useful, indeed. I will try to develop that, thanks for your input! :)

**Comment by marcelotrevisani** [comment]
Added in 
 - https://github.com/marcelotrevisani/souschef/pull/30
