### ISSUE TITLE
How to add a new (sub) section (e.g. build: noarch: python)

### ISSUE THREAD

**Issue by sgbaird** [marcelotrevisani/souschef#29]
```python
my_recipe["build"]["noarch"]
```
gives a message about needing to try to create the section first.

> ```python
> KeyError('Index noarch does not exist. Try to create it first.')
> ```

Is this the intended method for "creation"?
```python
my_recipe["build"]["noarch"] = []
```

The following produced an error:
```python
my_recipe["build"].add_section("noarch")
```

**Comment by sgbaird** [comment]
```python
my_recipe["build"]["noarch"] = []
my_recipe["build"]["noarch"].append(
```
`meta.yaml`
```python
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

  noarch: # new
    - python # new
```

> ```python
> (base) PS C:\Users\sterg\Documents\GitHub\sparks-baird\mat_discover\scratch>cconda build .
> No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
> WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
> Traceback (most recent call last):
>   File "C:\Users\sterg\Miniconda3\Scripts\conda-build-script.py", line 10, in <module>
>     sys.exit(main())
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 481, in main
>     execute(sys.argv[1:])
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 470, in execute
>     outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\api.py", line 186, in build
>     return build_tree(
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\build.py", line 3064, in build_tree
>     metadata_tuples = render_recipe(recipe, config=cfg, variants=variants,    
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\render.py", line 829, in render_recipe
>     m = MetaData(recipe_dir, config=config)
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\metadata.py", line 927, in __init__
>     self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=True)
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\metadata.py", line 1002, in parse_again
>     self.meta = parse(self._get_contents(permit_undefined_jinja,
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\metadata.py", line 363, in parse
>     ensure_valid_noarch_value(res)
>   File "C:\Users\sterg\Miniconda3\lib\site-packages\conda_build\metadata.py", line 276, in ensure_valid_noarch_value
>     raise exceptions.CondaBuildException("Invalid value for noarch: %s" % build_noarch)
> conda_build.exceptions.CondaBuildException: Invalid value for noarch: ['python']
> ```

I tried playing around with `my_recipe["build"].add_section()` as well.

**Comment by sgbaird** [comment]
I think I got it:
```python
my_recipe["build"]["noarch"] = "python"
```

> ```python
> build:
>   number: 0
>   script: {{ PYTHON }} -m pip install . -vv
> 
>   noarch: python
> ```

**Comment by marcelotrevisani** [comment]
yeah, ``noarch`` should be just one string

```
my_recipe["build"].add_section("noarch")
```
should work, I will investigate the reason it is not functioning, thanks for reporting it!

**Comment by marcelotrevisani** [comment]
Fixed in:
 - https://github.com/marcelotrevisani/souschef/pull/31

**Comment by marcelotrevisani** [comment]
I will generate a new version with those fixes and new functionalities.
Thank you very much for your input!

**Comment by marcelotrevisani** [comment]
The version ``0.2.0`` is already on pypi
 - https://pypi.org/project/conda-souschef/

I will upload it for conda-forge as well, it should appear in the conda-forge channel in one hour or so

**Comment by sgbaird** [comment]
Awesome!! Thanks for the super-quick responses and updates! I've really appreciated the help with this. I now have some automated workflows going from `flit` to `grayskull` to `conda build` using `conda-souschef`.

**Comment by marcelotrevisani** [comment]
I really appreciate your feedback, thanks a lot! If you have new suggestions or bug reports please feel free to open them :)

Pretty nice your workflow, I would love to take a look at it if possible
