### ISSUE TITLE
append Ingredient to "about" section (e.g. `doc_url`)

### ISSUE THREAD

**Issue by sgbaird** [marcelotrevisani/souschef#46]
```python
my_recipe["about"]
<Section about>
special variables
function variables
add_section:<function AddSection.add_section at 0x0000022D79D6D280>
add_section_str:<bound method AddSection.add_section_str of <Section about>>
insert:<bound method GetSetItemMixin.insert of <Section about>>
items:<bound method Section.items of <Section about>>
keys:<bound method Section.keys of <Section about>>
update:<bound method Section.update of <Section about>>
values:<bound method Section.values of <Section about>>
inline_comment:None
selector:None
value:[home: https://github.../xtal2png/, summary: Encode and ...NG) files., dev_url: https://git.../xtal2png/, license: MIT, license_file: LICENSE.txt, '']
yaml:ordereddict([('home', 'https://github.com/sparks-baird/xtal2png/'), ('summary', 'Encode and decode crystal structures via portable networks graphics (PNG) files.'), ('dev_url', 'https://github.com/sparks-baird/xtal2png/'), ('license', 'MIT'), ('license_file', 'LICENSE.txt')])
_GetSetItemMixin__add_comment_to_list:<bound method GetSetItemMixin.__add_comment_to_list of <Section about>>
_GetSetItemMixin__add_value_right_position:<bound method GetSetItemMixin.__add_value_right_position of <Section about>>
_GetSetItemMixin__get_all_comments_after_position:<bound method GetSetItemMixin.__get_all_comments_after_position of <Section about>>
_GetSetItemMixin__insert_value_position:<bound method GetSetItemMixin.__insert_value_position of <Section about>>
_GetSetItemMixin__re_add_comments:<bound method GetSetItemMixin.__re_add_comments of <Section about>>
_GetSetItemMixin__set_list_val:<bound method GetSetItemMixin.__set_list_val of <Section about>>
_Section__yaml:<weakref at 0x0000022D79DC2540; to 'CommentedMap' at 0x0000022D79D90400>
_config:<weakref at 0x0000022D79DC2680; to 'RecipeConfiguration' at 0x0000022D79B95FD0>
_get_yaml_comment:<bound method InlineCommentMixin._get_yaml_comment of <Section about>>
_name:'about'
_parent:<weakref at 0x0000022D79DC2630; to 'CommentedMap' at 0x0000022D79D90040>
```

("prettier" version)
<img src=https://user-images.githubusercontent.com/45469701/170584821-499a6d79-bd45-48d4-823d-c5c6d5924b26.png width=200>

I've tried using `my_recipe["about"].insert(0, ...)`  with various things (`str`, `Ingredient`, etc.). Maybe I'm missing something basic?

Was trying to add a `doc_url` to the `about` Section

**Comment by sgbaird** [comment]
A few things I've tried:
```python
my_recipe["about"].insert(0, "some_url")
```

> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\souschef\mixins.py", line 260, in insert
>     self.__add_value_right_position(Comment, index, value)
>   File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\souschef\mixins.py", line 271, in __add_value_right_position
>     self.__insert_value_position(index, value)
>   File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\souschef\mixins.py", line 239, in __insert_value_position
>     self.yaml.insert(index, pkg_info)
> TypeError: insert() missing 1 required positional argument: 'value'
> ```

```python
my_recipe["about"].insert(0, "key", "value")
```

> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> TypeError: insert() takes 3 positional arguments but 4 were given
> ```

```python
my_recipe["about"].insert(0, {"key": "value"})
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\souschef\mixins.py", line 249, in insert
    is_comment = re.match(r"^\s*#", value) is not None
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

```python
my_recipe["about"].insert(0, Ingredient(my_recipe["about"]))
```

> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\souschef\mixins.py", line 249, in insert
>     is_comment = re.match(r"^\s*#", value) is not None
>   File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\re.py", line 191, in match
>     return _compile(pattern, flags).match(string)
> TypeError: expected string or bytes-like object
> ```

## 
As well as playing around with `add_section_str` and trying to append to `my_recipe["about"].value`, but not really knowing how to instantiate a custom `Ingredient`:

```python
my_recipe["about"].value
```
> [home: https://github.../xtal2png/, summary: Encode and ...NG) files., dev_url: https://git.../xtal2png/, license: MIT, license_file: LICENSE.txt, '']
```python
my_recipe["about"].value[0]
```
> home: https://github.com/sparks-baird/xtal2png/
```python
type(my_recipe["about"].value[0])
```

> <class 'souschef.ingredient.Ingredient'>
> special variables
> constrains:<property object at 0x000001BBFC5D12C0>
> inline_comment:<property object at 0x000001BBFC5B9630>
> package_name:<property object at 0x000001BBFC5D1310>
> selector:<property object at 0x000001BBFC5B9720>
> value:<property object at 0x000001BBFC5D1270>
> yaml:<property object at 0x000001BBFC5D1130>
> _get_yaml_comment:<function InlineCommentMixin._get_yaml_comment at 0x000001BBFC5BE5E0>
> 

```python
type(my_recipe["about"].value)
```
> <class 'list'>

**Comment by sgbaird** [comment]
If it helps here's the `meta.yaml` recipe I'm working with:
https://github.com/conda-forge/staged-recipes/pull/19083/files

**Comment by marcelotrevisani** [comment]
gonna take a look at this, it was working before, maybe I messed something up :/
Thanks for reporting it

**Comment by marcelotrevisani** [comment]
so, you can do:
```python
my_recipe["about"]["doc_url"] = "your url"
```
or
```python
my_recipe["about"] = {"doc_url": "your url"}
```

**Comment by marcelotrevisani** [comment]
the insert in that case is used just when we have lists and such. I know, a bit confusing, sorry bout that

**Comment by sgbaird** [comment]
@marcelotrevisani oh my! So simple haha. Thank you!

**Comment by sgbaird** [comment]
xref: https://github.com/marcelotrevisani/souschef/issues/47#issuecomment-1146737438
