### ISSUE TITLE
The recipe is not parsable by parser conda-souschef (grayskull)

### ISSUE THREAD

**Issue by kurapov-peter** [marcelotrevisani/souschef#60]
Hi folks,

We've got a lintner warning about the unparsable recipe (https://github.com/conda-forge/level-zero-feedstock/pull/44#issuecomment-2489635760). I went through the CI logs but found nothing that would hint at what was wrong. Is there a way to run the parser locally?

**Comment by carterbox** [comment]
The `conda-forge-admin` will now include a link to the logs at the bottom of its message. An example [is here](https://github.com/conda-forge/staged-recipes/pull/28355#issuecomment-2499051989). Please close this issue until the next time you rerender your feedstock and have a chance to look at the logs from the linter (these logs are separate from the conda-build logs).

**Comment by kurapov-peter** [comment]
Thanks. Closing for now.
